version: '3.7'

services:
  db:
    image: mysql:8
    container_name: db_test_db
    env_file:
      - .env
    networks:
      - db-test
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    restart: no
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 10

  cli:
    build:
      dockerfile: Dockerfile
      target: php-cli-base
    container_name: db_test_cli
    working_dir: /var/www/db_test
    env_file:
      - .env
    volumes:
      - './:/var/www/db_test'
    command: 'tail -f /dev/null'
    networks:
      - db-test
    restart: no
    depends_on:
      db:
        condition: service_healthy

networks:
  db-test:
    name: db-test
    driver: bridge